name: webapp_dev_commit

on:
  push:
    branches:
      - dev

env:
    AZURE_RESOURCEGROUP_NAME: BicepAndGitHub-DEV-RG
    ENVIRONMENT: DEV

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of the repo on a ubuntu-latest runner
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZCRED_DEV }}
    
    # Deploy template
    - name: Deploy template
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./Bicep/webapp.bicep
        parameters: environment=${{ env.ENVIRONMENT }} webAppName=DemoWebApp