name: webapp_dev_commit

on: workflow_dispatch

env:
    AZURE_RESOURCEGROUP_NAME: BicepAndGitHub-DEV-RG
    ENVIRONMENT: DEV
    BICEPFILE: ./Bicep/webapp.bicep

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of the repo on a ubuntu-latest runner
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Transpile bicep and check for linter errors
    - name: Build ARM Template from bicep file
      # run: |
      # az bicep build --file ${{ env.BICEPFILE }}
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: ${{ env.BICEPFILE }}
        outputFilePath: azuredeploy.json

    # Login to Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZCRED_DEV }}
    
    # Deploy template
    - name: Deploy template
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ${{ env.BICEPFILE }}
        parameters: environment=${{ env.ENVIRONMENT }} webAppName=DemoWebApp